### ISSUE TITLE
wrong label for electrodes

### ISSUE THREAD

**Issue by ALJouen** [fcbg-hnp/mnelab#22]
Hello, 

I have been using your toolbox a lot recently and I have a weird issue: when I import my .sef file, the name of the electrodes contains an additional letter (a X or V, e.g: A5V) which is not present in my original Cartool file!
This is not a big issue but, of course, there is a conflit when I try to load the bad electrodes file because the names are not matching.
What should I do to avoid that? It's recent, yesterday it was fine. 
Thanks in advance

ALJ

![erreurMnelab](https://user-images.githubusercontent.com/52032332/59837278-43287300-934d-11e9-903c-f358577a3d97.png)

**Comment by ALJouen** [comment]
Correction: it causes a big issue later since it does not correspond to the Biosemi montage.
I am going to try to understand why I have this additionnal letter appearing that I don't see in Cartool...
Thanks in advance for your help

**Comment by TyWR** [comment]
Hi, 

As a temporary solution, it is still possible to manually change the name of each electrode by going in the menu Edit > Edit Channel Properties.

Is the problem happening directly after you loaded the file, or after the filter was used ? In the first case, it is likely that the names in the .sef format were already wrongly formatted. (You can check it out by opening the .sef format in a text editor and look a the rows). On my linux computer it doesn't seem to be bugging with .sef files.

**Comment by ALJouen** [comment]
Hi, 

Thanks for your answer!

Apparently I don't have the same issue with .vhdr so I will use this format for now (instead ot the manual change which will take too much time).

The problem happens directly after I load the file, I did't not use the filters in MNELAB (only the ones in cartool).

Do you have a recommandation for the text editor? I tried with notepad ++ but seems unable to read the .sef  
Even if, indeed, it seems that the channels are not correclty labelled in this file (I guess the channels are the one with the W)
SE01€        
    Dâ   &    A1 È"½WA2 È"½WA3 È"½WA4 È"½WA5 È"½WA6 È"½WA7 È"½WA8 È"½WA9 È"½WA10 È"½WA11 È"½WA12 È"½WA13 È"½WA14 È"½WA15 È"½WA16 È"½WA17 È"½WA18 È"½WA19 È"½WA20 È"½WA21 È"½WA22 È"½WA23 È"½WA24 È"½WA25 È"½WA26 È"½WA27 È"½WA28 È"½WA29 È"½WA30 È"½WA31 È"½WA32 È"½WB1  È"½WB2  È"½WB3  È"½WB4  È"½WB5  È"½WB6  È"½WB7  È"½WB8  È"½WB9  È"½WB10 È"½WB11 È"½WB12 È"½WB13 È"½WB14 È"½WB15 È"½WB16 È"½WB17 È"½WB18 È"½WB19 È"½WB20 È"½WB21 È"½WB22 È"½WB23 È"½WB24 È"½WB25 È"½WB26 È"½WB27 È"½WB28 È"½WB29 È"½WB30 È"½WB31 È"½WB32 È"½WC1  È"½WC2  È"½WC3  È"½WC4  È"½WC5  È"½WC6  È"½WC7  È"½WC8  È"½WC9  È"½WC10 È"½WC11 È"½WC12 È"½WC13 È"½WC14 È"½WC15 È"½WC16 È"½WC17 È"½WC18 È"½WC19 È"½WC20 È"½WC21 È"½WC22 È"½WC23 È"½WC24 È"½WC25 È"½WC26 È"½WC27 È"½WC28 È"½WC29 È"½WC30 È"½WC31 È"½WC32 È"½WD1  È"½WD2  È"½WD3  È"½WD4  È"½WD5  È"½WD6  È"½WD7  È"½WD8  È"½WD9  È"½WD10 È"½WD11 È"½WD12 È"½WD13 È"½WD14 È"½WD15 È"½WD16 È"½WD17 È"½WD18 È"½WD19 È"½WD20 È"½WD21 È"½WD22 È"½WD23 È"½WD24 È"½WD25 È"½WD26 È"½WD27 È"½WD28 È"½WD29 È"½WD30 È"½WD31 È"½WD32 È"½W4Ü@9‰™?U‡_AOIA}?`A—Iæ@d¦ë@˜ä¾dˆÁBõµ@–wÁÉƒÁ`Õ§Á•ãÁÊ‡Áz÷RÁ‚ñbÁÍì@vç[AT‡ü@òÌ	AÂïù¿LddÁÒË­Á~ôÁ­§>Á¼oÁÐøxÁîÕÁÐ©À\¥£ÁTÏy@x5AŽ_A¨!@@é.@T¯A¶¸HÀ1ÒSÀHkîÁñÁ  ºÁñôŸÁåQ“Áx/£ÀfVÕÁANÁ`¥œÀè6®@îw@„#AZV+A=$HAY`˜>\AüFÀôDJÀþ¾œÁÔ*3Á‚!¤ÀC]HÁ»l˜Àº,„Á¤[û¿›Ô@ãA>A´
_A„¼ @}½Àý(“@~¯LÁ†ogÁ>Ä³¿q*äÀnÿ‘ÁZ%,Aã
A¨#JÀ*ŒÀ; 7ÁûØÝÀÚfOÀÌ9[Àª£?¹è’@ºi?˜€ë@Æä3AlàéÀöP¢Á

The weird thing is that I did exactly the same steps yesterday: same participant, same preprocessing... and I don't have the problem when I open this datafile from yesterday (I compared the verbose of the 2 datasets but I don't see any difference). Plus, I did not update MNELAB before seeing the error.

If you have any idea... Maybe it is related to cartool but when I open the data with this software, the labels are correct...

Thanks

ALJ

**Comment by ALJouen** [comment]
Same file open simulatenously in MNELAB and Cartool! 

![erreurMnelab2](https://user-images.githubusercontent.com/52032332/59851105-0c158a00-936c-11e9-9f77-b69204899c86.png)

**Comment by vferat** [comment]
Can you attach one or send by email at victor.ferat@fcbg one .sef file for which the problem occurs ? ( if you can share your data)

**Comment by ALJouen** [comment]
Sure, I'll send a dropbox link by email
Too heavy,
TY

**Comment by vferat** [comment]
Fixed with [commit](https://github.com/fcbg-hnp/mnelab/commit/be6e06ade671c88356d6969bd26f113c7ec2ea75)

**Comment by ALJouen** [comment]
Problem fixed! Thanks
